name: Test

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v17
      - run: sudo pip install GitPython
      - run: src/get-maintained.sh
      - run: python3 src/wc_main.py 000-maintained
      - run: python3 src/wc_main.py 000-test
      - run: git diff
      - run: git diff --quiet

